name: common-data-elements 

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.11
  - jupyterlab
  - pandas
  - openpyxl
  - pyarrow
  - titlecase
  - levenshtein
  - tqdm
  - matplotlib
  - seaborn
  - scikit-learn
  - python-dotenv
  - black
  - papermill
  - openjdk=17.0.8
  - python-dotenv
